### PR TITLE
bugfix: robust removeAlgQuadsRecursive & fix unary operator generation

### LINKED ISSUE #100: Traqula toAst copy not able to handle undefined
Looking at https://github.com/comunica/comunica/issues/1655 it seems like Traqula cannot handle undefined in `removeAlgQuadsRecursive`, however, Comunica adds metadata to the algebra and this should remain untouched.

### PR DESCRIPTION
**Pull request by jitsedesmet**
Resolves #100

### CODE REVIEW

File: packages/algebra-transformations-1-1/lib/toAst/quads.ts [hunk 1]
```diff
@@ -27,7 +27,7 @@ unknown,
       return op.map(sub => SUBRULE(removeAlgQuadsRecursive, sub, graphs));
     }
 
-    if (!op.type) {
+    if (typeof op !== 'object' || op === null || !op.type) {
```
Comment (rubensworks) [inline packages/algebra-transformations-1-1/lib/toAst/quads.ts]: I wonder if there's a typing issue? I would expect `tsc` to have picked on this.

**Review by rubensworks — APPROVED** [review]

**Review by rubensworks — APPROVED** [review]
